### ISSUE TITLE
Extend libpe's API to support all the properties of PEV

### ISSUE THREAD

**Issue by boddumanohar** [merces/libpe#13]
Currently libpe API supports "sections", "headers", "Directories". We need to add support for other properties of the PEV like "hashes", "Imports", "exports", "resources", "relocations", "entrophy".

**Comment by jweyrich** [comment]
Merged in fd4cc8178479eeb89634979054519f1305da657f. Thank you!

**Comment by jweyrich** [comment]
@boddumanohar we still need to find what's causing those memory warnings/errors detected by valgrind.
I suspect it's caused by a memory corruption somewhere (possibly an overflow) - but haven't had the time to investigate yet.
