### ISSUE TITLE
Demo code returns `null` for imphash

### ISSUE THREAD

**Issue by boddumanohar** [merces/libpe#20]
when I run the demo code, At the end I see the output of imphash value as 
```
imphash: (null)
```

**Comment by boddumanohar** [comment]
when I try to print the value of `strdup(result)` in line [585](https://github.com/merces/libpe/blob/master/hashes.c#L585) 

it returns values like `ole32`, `oleaut32`, `advapi32`

**Comment by jweyrich** [comment]
Fixed it. The problem was related to a buffer size validation in `pe_hash_raw_data`.
However, it looks like the imphash we generate is not correct - needs further investigation.
