### ISSUE TITLE
Add pesec.c to libpe

### ISSUE THREAD

**Issue by boddumanohar** [merces/libpe#21]
I the pull #14 I did not move code of pesec.c

What I am assuming is that we going to move everything to libpe and make PEV use libpe as a dependency completely. If I am correct, we should move pesec.c code to libpe ( I will make of list of things that are yet to be moved) so that we can release the next version which completely uses libpe. This will make the code of PEV a lot cleaner.

**Comment by jweyrich** [comment]
Positive! We deeply appreciate your effort on this :-)

**Comment by merces** [comment]
I believe we've done most of it. Do you agree we can close it @jweyrich?

**Comment by jweyrich** [comment]
Agreed
