### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [merces/libpe#7]
[Extra null pointer checks are not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for NULL before free(p)?") in [the function "pe_unload"](https://github.com/merces/libpe/blob/36b8fd2561fa585734773e5f91d32234a61b6608/pe.c#L123 "Update candidate").

**Comment by jweyrich** [comment]
Nice! Would you like to send a pull request so we can merge it?

**Comment by jweyrich** [comment]
Was merged in https://github.com/merces/libpe/issues/8.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/MrN0body/libpe/commit/aa920d02a3f37f5c4a6e23ec6014cec858978945 "Deletion of unnecessary null pointer checks").
