### ISSUE TITLE
A small question

### ISSUE THREAD

**Issue by ghost** [merces/libpe#9]
Hello guys,

I didn't understand the reason for this ['if'](https://github.com/merces/libpe/blob/master/pe.c#L335). I think it will match with PE files having only one section in which the field VirtualAddress is greater than rva. In this case, is it rva pointing to some header? Wouldn't be better return the difference between rva and imagebase?

Cheers!

**Comment by merces** [comment]
Your question makes totally sense, @MrN0body. I'll investigate and get back to you, thanks!

**Comment by merces** [comment]
No idea where this code is. Closing it.
